
name: Clone the repo with actions using branch filter
on:
  push:
    branches:
      - test
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout using actions
        uses: actions/checkout@v4
      - name: show current directory
        run: pwd
      - name: List all the files
        run: ls -lrt
