name: Clone Private-repo

on:
  pull_request: 
    branches:
      - main
  workflow_dispatch: 

env:
  REPO: https://github.com/sayabugarisaikiran/streamflix-app.git

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone the private repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "cloning the private repo"
          git clone "$REPO"
          echo "key Value: $GH_TOKEN"
          cd "streamflix-app"
          ls -lrt
