name: Clone Private-repo

on:
  pull_request: 
    branches:
      - main
  workflow_dispatch: 

env:
  REPO: https://github.com/sayabugarisaikiran/movie-analyzer-project.git

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone the private repo
        run: |
          echo "cloning the private repo"
          git clone "$REPO"
          cd "$REPO"
          ls -lrt
